name: Run tests

on: [push, pull_request]

jobs:
  checkout:
    name: Checkout code
    runs-on: ubuntu-latest

    outputs:
      changelog: ${{ steps.changed-files.outputs.all_changed_files }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.4

      - name: Upload checkout
        uses: actions/upload-artifact@v3
        with:
          name: ${{$GITHUB_SHA}}
          path: .

  first_conditional:
    name: First member tests
    runs-on: ubuntu-latest

    needs: [checkout]
    if: contains(needs.checkout.outputs.changelog, 'first_member')

    steps:
      - name: Download checkout
        uses: actions/download-artifact@v3
        with:
          name: ${{$GITHUB_SHA}}

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --package first_member
        
  second_conditional:
    name: Second member tests
    runs-on: ubuntu-latest

    needs: [checkout]
    if: contains(needs.checkout.outputs.changelog, 'second_member')

    steps:
      - name: Download checkout
        uses: actions/download-artifact@v3
        with:
          name: ${{$GITHUB_SHA}}

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --package first_member

  release_version:
    name: Release version
    runs-on: ubuntu-latest

    needs: [
      first_conditional,
      second_conditional
    ]
    if: ${{ contains(github.event.head_commit.message, 'release') }}
    
    steps:
      - name: Download checkout
        uses: actions/download-artifact@v3
        with:
          name: ${{$GITHUB_SHA}}

      - name: Create tag
        id: tagging
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tagging.outputs.new_tag }}
          token: ${{ secrets.PAT }}
