name: Run tests

on: [push, pull_request]

jobs:
  checkout:
    name: Checkout code
    runs-on: ubuntu-latest

    outputs:
      changelog: ${{ steps.changed-files.outputs.all_changed_files }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.4

      - name: Upload checkout
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          path: .

  first_conditional:
    name: First member tests
    runs-on: ubuntu-latest

    needs: [checkout]
    if: contains(needs.checkout.outputs.changelog, 'first_member')

    steps:
      - name: Download checkout
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.sha }}

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --package first_member

  when_first_has_changed:
    name: When first has changed
    runs-on: ubuntu-latest

    needs: [first_conditional]

    steps:
      - name: Echo message
        run: echo "something to do"
        
  second_conditional:
    name: Second member tests
    runs-on: ubuntu-latest

    needs: [checkout]
    if: contains(needs.checkout.outputs.changelog, 'second_member')

    steps:
      - name: Download checkout
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.sha }}

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --package first_member

  when_first_and_second_have_changed:
    name: When first has changed
    runs-on: ubuntu-latest

    needs: [first_conditional, second_conditional]

    steps:
      - name: Echo message
        run: echo "something to do"

  release_version:
    name: Release version
    runs-on: ubuntu-latest

    needs: [
      first_conditional,
      second_conditional
    ]
    if: ${{ contains(github.event.head_commit.message, 'release') }}
    
    steps:
      - name: Download checkout
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.sha }}

      - name: Create tag
        id: tagging
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tagging.outputs.new_tag }}
          token: ${{ secrets.PAT }}

  clear_workspace: 
    name: Clear workspace
    runs-on: ubuntu-latest

    needs: [
      checkout,
      release_version,
      first_conditional,
      second_conditional,
      when_first_has_changed,
      when_first_and_second_have_changed
    ]

    if: ${{ always() }}

    steps:
      - name: Delete Artifact
        uses: GeekyEggo/delete-artifact@v1
        with:
          name: ${{ github.sha }}